// export  const DATA= {
//   "Apple": [
//     { "Company": "Apple", "ScriptCode": "12345", "Symbol": "EXMPL" },
//     { "Company": "Test Corp", "ScriptCode": "67890", "Symbol": "TEST" }
//   ],
//   "data": [
//     { "Company": "Example Co", "description": "Example Company Description", "details": "Example Company Details", "ScriptCode": "12345", "Symbol": "EXMPL" },
//     { "Company": "Test Corp", "description": "Test Corporation Description", "details": "Test Corporation Details", "ScriptCode": "67890", "Symbol": "TEST" }
//   ]
// }
export const DATA = {
  search: 
  [
    
    
 
	

    {
        "Id": 592009,
        "Company": "<b>HDFC</b> Bank Ltd.",
        "ScriptCode": 500180,
        "Symbol": "HDFCBANK",
        "url": "https://www.marketsmojo.com/stocks-analysis/hdfc-bank-592009-0",
        "price": null,
        "ExchangeName": "bse",
        "sname": "HDFC Bank",
        "tag": "Stock",
        "stockprice": "1608.50",
        "chg": "-17.75",
        "chgp": "-1.09",
        "chgdir": -1,
        "score": 88,
        "scoretext": "Strong Buy",
        "stock_traded_status": "Active",
        "show_score": 1,
        "recurl": ""
    },
    
    {
        "Id": 1002872,
        "Company": "<b>HDFC</b> Life Insurance Company Ltd",
        "ScriptCode": 540777,
        "Symbol": "HDFCLIFE",
        "url": "https://www.marketsmojo.com/stocks-analysis/hdfc-life-insurance-company-1002872-0",
        "price": null,
        "ExchangeName": "bse",
        "sname": "HDFC Life Insur.",
        "tag": "Stock",
        "stockprice": "635.50",
        "chg": "2.85",
        "chgp": "0.45",
        "chgdir": 1,
        "score": 51,
        "scoretext": "Hold",
        "stock_traded_status": "Active",
        "show_score": 1,
        "recurl": ""
    },
    {
        "Id": 1002872,
        "Company": "<b>HDFC</b> Life Insurance Company Ltd",
        "ScriptCode": 540777,
        "Symbol": "HDFCLIFE",
        "url": "https://www.marketsmojo.com/news/hdfc-life-insurance-company-ltd-1002872",
        "price": null,
        "ExchangeName": "bse",
        "sname": "HDFC Life Insur.",
        "tag": "News",
        "stockprice": "635.50",
        "chg": "2.85",
        "chgp": "0.45",
        "chgdir": 1,
        "score": 51,
        "scoretext": "Hold",
        "stock_traded_status": "Active",
        "show_score": 1,
        "recurl": ""
    },
    {
        "Id": 1003028,
        "Company": "<b>HDFC</b> Asset Management Company Ltd",
        "ScriptCode": "541729",
        "Symbol": "HDFCAMC",
        "url": "https://www.marketsmojo.com/stocks-analysis/hdfc-asset-management-company-1003028-0",
        "price": null,
        "ExchangeName": "bse",
        "sname": "HDFC AMC",
        "tag": "Stock",
        "stockprice": "4156.85",
        "chg": "10.05",
        "chgp": "0.24",
        "chgdir": 1,
        "score": 78,
        "scoretext": "Buy",
        "stock_traded_status": "Active",
        "show_score": 1,
        "recurl": ""
    },
    {
      "Id": 1003028,
      "Company": "<b>HDFC</b> Asset Management Company Ltd",
      "ScriptCode": "541729",
      "Symbol": "HDFCAMC",
      "url": "https://www.marketsmojo.com/news/hdfc-asset-management-company-ltd-1003028",
      "price": null,
      "ExchangeName": "bse",
      "sname": "HDFC AMC",
      "tag": "News",
      "stockprice": "4156.85",
      "chg": "10.05",
      "chgp": "0.24",
      "chgdir": 1,
      "score": 78,
      "scoretext": "Buy",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 741664,
      "Company": "Housing Development Finance CorporationLtd(Merged) - <b>HDFC</b>",
      "ScriptCode": 500010,
      "Symbol": "HDFC",
      "url": "https://www.marketsmojo.com/stocks-analysis/housing-development-finance-corporationltdmerged-741664-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "H D F C",
      "tag": "Stock",
      "stockprice": "",
      "chg": "",
      "chgp": "",
      "chgdir": "",
      "score": "",
      "scoretext": "",
      "stock_traded_status": "Not Traded",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 741664,
      "Company": "Housing Development Finance CorporationLtd(Merged) - <b>HDFC</b>",
      "ScriptCode": 500010,
      "Symbol": "HDFC",
      "url": "https://www.marketsmojo.com/news/housing-development-finance-corporationltd-merged--741664",
      "price": null,
      "ExchangeName": "bse",
      "sname": "H D F C",
      "tag": "News",
      "stockprice": "",
      "chg": "",
      "chgp": "",
      "chgdir": "",
      "score": "",
      "scoretext": "",
      "stock_traded_status": "Not Traded",
      "show_score": 1,
      "recurl": ""
  },
  
  //TATA
    {
        "Id": 513374,
        "Company": "<b>Tata</b> Consultancy Services Ltd.",
        "ScriptCode": 532540,
        "Symbol": "TCS",
        "url": "https://www.marketsmojo.com/stocks-analysis/tata-consultancy-services-513374-0",
        "price": null,
        "ExchangeName": "bse",
        "sname": "TCS",
        "tag": "Stock",
        "stockprice": "3912.20",
        "chg": "2.30",
        "chgp": "0.06",
        "chgdir": 1,
        "score": 75,
        "scoretext": "Buy",
        "stock_traded_status": "Active",
        "show_score": 1,
        "recurl": ""
    },
    {
      "Id": 513374,
      "Company": "<b>Tata</b> Consultancy Services Ltd.",
      "ScriptCode": 532540,
      "Symbol": "TCS",
      "url": "https://www.marketsmojo.com/news/tata-consultancy-services-ltd-513374",
      "price": null,
      "ExchangeName": "bse",
      "sname": "TCS",
      "tag": "News",
      "stockprice": "3912.20",
      "chg": "2.30",
      "chgp": "0.06",
      "chgdir": 1,
      "score": 75,
      "scoretext": "Buy",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 949886,
      "Company": "<b>Tata</b> Motors Ltd.",
      "ScriptCode": 500570,
      "Symbol": "TATAMOTORS",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-motors-949886-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Motors",
      "tag": "Stock",
      "stockprice": "1021.60",
      "chg": "16.15",
      "chgp": "1.61",
      "chgdir": 1,
      "score": 78,
      "scoretext": "Buy",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 949886,
      "Company": "<b>Tata</b> Motors Ltd.",
      "ScriptCode": 500570,
      "Symbol": "TATAMOTORS",
      "url": "https://www.marketsmojo.com/news/tata-motors-ltd-949886",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Motors",
      "tag": "News",
      "stockprice": "1021.60",
      "chg": "16.15",
      "chgp": "1.61",
      "chgdir": 1,
      "score": 78,
      "scoretext": "Buy",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 594470,
      "Company": "<b>Tata</b> Steel Ltd",
      "ScriptCode": 500470,
      "Symbol": "TATASTEEL",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-steel-594470-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Steel",
      "tag": "Stock",
      "stockprice": "169.90",
      "chg": "1.90",
      "chgp": "1.13",
      "chgdir": 1,
      "score": 61,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 594470,
      "Company": "<b>Tata</b> Steel Ltd",
      "ScriptCode": 500470,
      "Symbol": "TATASTEEL",
      "url": "https://www.marketsmojo.com/news/tata-steel-ltd-594470",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Steel",
      "tag": "News",
      "stockprice": "169.90",
      "chg": "1.90",
      "chgp": "1.13",
      "chgdir": 1,
      "score": 61,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 790869,
      "Company": "<b>Tata</b> Power Company Ltd",
      "ScriptCode": 500400,
      "Symbol": "TATAPOWER",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-power-company-790869-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Power Co.",
      "tag": "Stock",
      "stockprice": "441.35",
      "chg": "4.10",
      "chgp": "0.94",
      "chgdir": 1,
      "score": 58,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 790869,
      "Company": "<b>Tata</b> Power Company Ltd",
      "ScriptCode": 500400,
      "Symbol": "TATAPOWER",
      "url": "https://www.marketsmojo.com/news/tata-power-company-ltd-790869",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Power Co.",
      "tag": "News",
      "stockprice": "441.35",
      "chg": "4.10",
      "chgp": "0.94",
      "chgdir": 1,
      "score": 58,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 272806,
      "Company": "<b>Tata</b> Consumer Products Ltd",
      "ScriptCode": 500800,
      "Symbol": "TATACONSUM",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-consumer-products-272806-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Consumer",
      "tag": "Stock",
      "stockprice": "1142.40",
      "chg": "-8.85",
      "chgp": "-0.77",
      "chgdir": -1,
      "score": 72,
      "scoretext": "Buy",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 272806,
      "Company": "<b>Tata</b> Consumer Products Ltd",
      "ScriptCode": 500800,
      "Symbol": "TATACONSUM",
      "url": "https://www.marketsmojo.com/news/tata-consumer-products-ltd-272806",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Consumer",
      "tag": "News",
      "stockprice": "1142.40",
      "chg": "-8.85",
      "chgp": "-0.77",
      "chgdir": -1,
      "score": 72,
      "scoretext": "Buy",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 952728,
      "Company": "<b>Tata</b> Communications Ltd",
      "ScriptCode": 500483,
      "Symbol": "TATACOMM",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-communications-952728-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Comm",
      "tag": "Stock",
      "stockprice": "1851.15",
      "chg": "-3.25",
      "chgp": "-0.18",
      "chgdir": -1,
      "score": 36,
      "scoretext": "Sell",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 952728,
      "Company": "<b>Tata</b> Communications Ltd",
      "ScriptCode": 500483,
      "Symbol": "TATACOMM",
      "url": "https://www.marketsmojo.com/news/tata-communications-ltd-952728",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Comm",
      "tag": "News",
      "stockprice": "1851.15",
      "chg": "-3.25",
      "chgp": "-0.18",
      "chgdir": -1,
      "score": 36,
      "scoretext": "Sell",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 949649,
      "Company": "<b>Tata</b> Elxsi Ltd.",
      "ScriptCode": "500408",
      "Symbol": "TATAELXSI",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-elxsi-949649-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Elxsi",
      "tag": "Stock",
      "stockprice": "6984.00",
      "chg": "-134.80",
      "chgp": "-1.89",
      "chgdir": -1,
      "score": 42,
      "scoretext": "Sell",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 949649,
      "Company": "<b>Tata</b> Elxsi Ltd.",
      "ScriptCode": "500408",
      "Symbol": "TATAELXSI",
      "url": "https://www.marketsmojo.com/news/tata-elxsi-ltd-949649",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Elxsi",
      "tag": "News",
      "stockprice": "6984.00",
      "chg": "-134.80",
      "chgp": "-1.89",
      "chgdir": -1,
      "score": 42,
      "scoretext": "Sell",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 10039079,
      "Company": "<b>Tata</b> Technologies Ltd",
      "ScriptCode": "544028",
      "Symbol": "TATATECH",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-technologies-10039079-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Technolog.",
      "tag": "Stock",
      "stockprice": "1013.85",
      "chg": "2.75",
      "chgp": "0.27",
      "chgdir": 1,
      "score": 55,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 10039079,
      "Company": "<b>Tata</b> Technologies Ltd",
      "ScriptCode": "544028",
      "Symbol": "TATATECH",
      "url": "https://www.marketsmojo.com/news/tata-technologies-ltd-10039079",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Technolog.",
      "tag": "News",
      "stockprice": "1013.85",
      "chg": "2.75",
      "chgp": "0.27",
      "chgdir": 1,
      "score": 55,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 302622,
      "Company": "<b>Tata</b> Motors - DVR Ordinary",
      "ScriptCode": 570001,
      "Symbol": "TATAMTRDVR",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-motors-dvr-ordinary-302622-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Motors - DVR",
      "tag": "Stock",
      "stockprice": "694.00",
      "chg": "10.95",
      "chgp": "1.60",
      "chgdir": 1,
      "score": "",
      "scoretext": "Not Rated",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 302622,
      "Company": "<b>Tata</b> Motors - DVR Ordinary",
      "ScriptCode": 570001,
      "Symbol": "TATAMTRDVR",
      "url": "https://www.marketsmojo.com/news/tata-motors-dvr-ordinary-302622",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Motors - DVR",
      "tag": "News",
      "stockprice": "694.00",
      "chg": "10.95",
      "chgp": "1.60",
      "chgdir": 1,
      "score": "",
      "scoretext": "Not Rated",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 371122,
      "Company": "<b>Tata</b> Investment Corporation Ltd",
      "ScriptCode": 501301,
      "Symbol": "TATAINVEST",
      "url": "https://www.marketsmojo.com/stocks-analysis/tata-investment-corporation-371122-0",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Inv.Corpn.",
      "tag": "Stock",
      "stockprice": "6421.05",
      "chg": "-20.95",
      "chgp": "-0.33",
      "chgdir": -1,
      "score": 62,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
  {
      "Id": 371122,
      "Company": "<b>Tata</b> Investment Corporation Ltd",
      "ScriptCode": 501301,
      "Symbol": "TATAINVEST",
      "url": "https://www.marketsmojo.com/news/tata-investment-corporation-ltd-371122",
      "price": null,
      "ExchangeName": "bse",
      "sname": "Tata Inv.Corpn.",
      "tag": "News",
      "stockprice": "6421.05",
      "chg": "-20.95",
      "chgp": "-0.33",
      "chgdir": -1,
      "score": 62,
      "scoretext": "Hold",
      "stock_traded_status": "Active",
      "show_score": 1,
      "recurl": ""
  },
//infosys

{
  "Id": 399834,
  "Company": "<b>Infosys</b> Ltd.",
  "ScriptCode": 500209,
  "Symbol": "INFY",
  "url": "https://www.marketsmojo.com/stocks-analysis/infosys-399834-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Infosys",
  "tag": "Stock",
  "stockprice": "1651.70",
  "chg": "4.00",
  "chgp": "0.24",
  "chgdir": 1,
  "score": 70,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 399834,
  "Company": "<b>Infosys</b> Ltd.",
  "ScriptCode": 500209,
  "Symbol": "INFY",
  "url": "https://www.marketsmojo.com/news/infosys-ltd-399834",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Infosys",
  "tag": "News",
  "stockprice": "1651.70",
  "chg": "4.00",
  "chgp": "0.24",
  "chgdir": 1,
  "score": 70,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 896075,
  "Company": "Eco Recycling Ltd - <b>InfoSys</b>c",
  "ScriptCode": 530643,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/eco-recycling-896075-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Eco Recyc.",
  "tag": "Stock",
  "stockprice": "759.00",
  "chg": "15.95",
  "chgp": "2.15",
  "chgdir": 1,
  "score": 64,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 896075,
  "Company": "Eco Recycling Ltd - <b>InfoSys</b>c",
  "ScriptCode": 530643,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/eco-recycling-ltd-896075",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Eco Recyc.",
  "tag": "News",
  "stockprice": "759.00",
  "chg": "15.95",
  "chgp": "2.15",
  "chgdir": 1,
  "score": 64,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 386301,
  "Company": "HCL <b>Infosys</b>tems Ltd",
  "ScriptCode": 500179,
  "Symbol": "HCL-INSYS",
  "url": "https://www.marketsmojo.com/stocks-analysis/hcl-infosystems-386301-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "HCL Infosystems",
  "tag": "Stock",
  "stockprice": "16.50",
  "chg": "-0.05",
  "chgp": "-0.30",
  "chgdir": -1,
  "score": 12,
  "scoretext": "Strong Sell",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 386301,
  "Company": "HCL <b>Infosys</b>tems Ltd",
  "ScriptCode": 500179,
  "Symbol": "HCL-INSYS",
  "url": "https://www.marketsmojo.com/news/hcl-infosystems-ltd-386301",
  "price": null,
  "ExchangeName": "bse",
  "sname": "HCL Infosystems",
  "tag": "News",
  "stockprice": "16.50",
  "chg": "-0.05",
  "chgp": "-0.30",
  "chgdir": -1,
  "score": 12,
  "scoretext": "Strong Sell",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 10039240,
  "Company": "Slone <b>Infosys</b>tems Ltd",
  "ScriptCode": 92903,
  "Symbol": "SLONE",
  "url": "https://www.marketsmojo.com/stocks-analysis/slone-infosystems-10039240-1",
  "price": null,
  "ExchangeName": "nse",
  "sname": "Slone",
  "tag": "Stock",
  "stockprice": "156.00",
  "chg": "-3.65",
  "chgp": "-2.29",
  "chgdir": -1,
  "score": "",
  "scoretext": "Not Rated",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 10039240,
  "Company": "Slone <b>Infosys</b>tems Ltd",
  "ScriptCode": 92903,
  "Symbol": "SLONE",
  "url": "https://www.marketsmojo.com/news/slone-infosystems-ltd-10039240",
  "price": null,
  "ExchangeName": "nse",
  "sname": "Slone",
  "tag": "News",
  "stockprice": "156.00",
  "chg": "-3.65",
  "chgp": "-2.29",
  "chgdir": -1,
  "score": "",
  "scoretext": "Not Rated",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002688,
  "Company": "Southern <b>Infosys</b> Ltd",
  "ScriptCode": 540174,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/southern-infosys-1002688-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Southern Infosys",
  "tag": "Stock",
  "stockprice": "26.03",
  "chg": "1.23",
  "chgp": "4.96",
  "chgdir": 1,
  "score": 57,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002688,
  "Company": "Southern <b>Infosys</b> Ltd",
  "ScriptCode": 540174,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/southern-infosys-ltd-1002688",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Southern Infosys",
  "tag": "News",
  "stockprice": "26.03",
  "chg": "1.23",
  "chgp": "4.96",
  "chgdir": 1,
  "score": 57,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 192803,
  "Company": "Shyama <b>Infosys</b> Ltd",
  "ScriptCode": 531219,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/shyama-infosys-192803-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Shyama Infosys",
  "tag": "Stock",
  "stockprice": "5.62",
  "chg": "-0.28",
  "chgp": "-4.75",
  "chgdir": -1,
  "score": "",
  "scoretext": "Not Rated",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 192803,
  "Company": "Shyama <b>Infosys</b> Ltd",
  "ScriptCode": 531219,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/shyama-infosys-ltd-192803",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Shyama Infosys",
  "tag": "News",
  "stockprice": "5.62",
  "chg": "-0.28",
  "chgp": "-4.75",
  "chgdir": -1,
  "score": "",
  "scoretext": "Not Rated",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 777263,
  "Company": "Palsoft <b>Infosys</b>tems Ltd (Delisted)",
  "ScriptCode": 511597,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/palsoft-infosystems-777263-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Palsoft Infosys.",
  "tag": "Stock",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 777263,
  "Company": "Palsoft <b>Infosys</b>tems Ltd (Delisted)",
  "ScriptCode": 511597,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/palsoft-infosystems-ltd-777263",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Palsoft Infosys.",
  "tag": "News",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 317876,
  "Company": " (Delisted) - Websity <b>Infosys</b>",
  "ScriptCode": 511415,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/-317876-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": null,
  "tag": "Stock",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 317876,
  "Company": " (Delisted) - Websity <b>Infosys</b>",
  "ScriptCode": 511415,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/-317876",
  "price": null,
  "ExchangeName": "bse",
  "sname": null,
  "tag": "News",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 779494,
  "Company": "Diamond <b>Infosys</b>tems Ltd (Delisted)",
  "ScriptCode": 530801,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/diamond-infosystems-779494-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Diamond Infosys.",
  "tag": "Stock",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 779494,
  "Company": "Diamond <b>Infosys</b>tems Ltd (Delisted)",
  "ScriptCode": 530801,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/diamond-infosystems-ltd-779494",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Diamond Infosys.",
  "tag": "News",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 861770,
  "Company": "Compudyne W<b>infosys</b>tems Ltd (Delisted)",
  "ScriptCode": 532306,
  "Symbol": "COMPUDYNE",
  "url": "https://www.marketsmojo.com/stocks-analysis/compudyne-winfosystems-861770-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Compudyne Win",
  "tag": "Stock",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 861770,
  "Company": "Compudyne W<b>infosys</b>tems Ltd (Delisted)",
  "ScriptCode": 532306,
  "Symbol": "COMPUDYNE",
  "url": "https://www.marketsmojo.com/news/compudyne-winfosystems-ltd-861770",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Compudyne Win",
  "tag": "News",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
//ICIici
{
  "Id": 478299,
  "Company": "<b>ICICI</b> Bank Ltd.",
  "ScriptCode": 532174,
  "Symbol": "ICICIBANK",
  "url": "https://www.marketsmojo.com/stocks-analysis/icici-bank-478299-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Bank",
  "tag": "Stock",
  "stockprice": "1230.00",
  "chg": "-12.45",
  "chgp": "-1.00",
  "chgdir": -1,
  "score": 84,
  "scoretext": "Strong Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 478299,
  "Company": "<b>ICICI</b> Bank Ltd.",
  "ScriptCode": 532174,
  "Symbol": "ICICIBANK",
  "url": "https://www.marketsmojo.com/news/icici-bank-ltd-478299",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Bank",
  "tag": "News",
  "stockprice": "1230.00",
  "chg": "-12.45",
  "chgp": "-1.00",
  "chgdir": -1,
  "score": 84,
  "scoretext": "Strong Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002663,
  "Company": "<b>ICICI</b> Prudential Life Insurance Company Ltd",
  "ScriptCode": 540133,
  "Symbol": "ICICIPRULI",
  "url": "https://www.marketsmojo.com/stocks-analysis/icici-prudential-life-insurance-company-1002663-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Pru Life",
  "tag": "Stock",
  "stockprice": "660.80",
  "chg": "0.25",
  "chgp": "0.04",
  "chgdir": 1,
  "score": 62,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002663,
  "Company": "<b>ICICI</b> Prudential Life Insurance Company Ltd",
  "ScriptCode": 540133,
  "Symbol": "ICICIPRULI",
  "url": "https://www.marketsmojo.com/news/icici-prudential-life-insurance-company-ltd-1002663",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Pru Life",
  "tag": "News",
  "stockprice": "660.80",
  "chg": "0.25",
  "chgp": "0.04",
  "chgdir": 1,
  "score": 62,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002823,
  "Company": "<b>ICICI</b> Lombard General Insurance Company Ltd",
  "ScriptCode": 540716,
  "Symbol": "ICICIGI",
  "url": "https://www.marketsmojo.com/stocks-analysis/icici-lombard-general-insurance-company-1002823-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Lombard",
  "tag": "Stock",
  "stockprice": "1880.00",
  "chg": "0.35",
  "chgp": "0.02",
  "chgdir": 1,
  "score": 72,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002823,
  "Company": "<b>ICICI</b> Lombard General Insurance Company Ltd",
  "ScriptCode": 540716,
  "Symbol": "ICICIGI",
  "url": "https://www.marketsmojo.com/news/icici-lombard-general-insurance-company-ltd-1002823",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Lombard",
  "tag": "News",
  "stockprice": "1880.00",
  "chg": "0.35",
  "chgp": "0.02",
  "chgdir": 1,
  "score": 72,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002957,
  "Company": "<b>ICICI</b> Securities Ltd",
  "ScriptCode": 541179,
  "Symbol": "ISEC",
  "url": "https://www.marketsmojo.com/stocks-analysis/icici-securities-1002957-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Securities",
  "tag": "Stock",
  "stockprice": "776.55",
  "chg": "-2.85",
  "chgp": "-0.37",
  "chgdir": -1,
  "score": 82,
  "scoretext": "Strong Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1002957,
  "Company": "<b>ICICI</b> Securities Ltd",
  "ScriptCode": 541179,
  "Symbol": "ISEC",
  "url": "https://www.marketsmojo.com/news/icici-securities-ltd-1002957",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Securities",
  "tag": "News",
  "stockprice": "776.55",
  "chg": "-2.85",
  "chgp": "-0.37",
  "chgdir": -1,
  "score": 82,
  "scoretext": "Strong Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 262956,
  "Company": "<b>ICICI</b> Ltd (Merged)",
  "ScriptCode": 500015,
  "Symbol": "ICICI",
  "url": "https://www.marketsmojo.com/stocks-analysis/icici-ltd-merged-262956-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI-Merged",
  "tag": "Stock",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 262956,
  "Company": "<b>ICICI</b> Ltd (Merged)",
  "ScriptCode": 500015,
  "Symbol": "ICICI",
  "url": "https://www.marketsmojo.com/news/icici-ltd-merged--262956",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI-Merged",
  "tag": "News",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1001449,
  "Company": "<b>ICICI</b> Bank (PP) (Delisted)",
  "ScriptCode": 890124,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/icici-bank-pp-1001449-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Bank (PP)",
  "tag": "Stock",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1001449,
  "Company": "<b>ICICI</b> Bank (PP) (Delisted)",
  "ScriptCode": 890124,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/icici-bank-pp--1001449",
  "price": null,
  "ExchangeName": "bse",
  "sname": "ICICI Bank (PP)",
  "tag": "News",
  "stockprice": "",
  "chg": "",
  "chgp": "",
  "chgdir": "",
  "score": "",
  "scoretext": "",
  "stock_traded_status": "Not Traded",
  "show_score": 1,
  "recurl": ""
},
//RAil
{
  "Id": 1003455,
  "Company": "Indian <b>Rail</b>way Finance Corporation Ltd",
  "ScriptCode": "543257",
  "Symbol": "IRFC",
  "url": "https://www.marketsmojo.com/stocks-analysis/indian-railway-finance-corporation-1003455-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "I R F C",
  "tag": "Stock",
  "stockprice": "205.30",
  "chg": "1.65",
  "chgp": "0.81",
  "chgdir": 1,
  "score": 58,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003455,
  "Company": "Indian <b>Rail</b>way Finance Corporation Ltd",
  "ScriptCode": "543257",
  "Symbol": "IRFC",
  "url": "https://www.marketsmojo.com/news/indian-railway-finance-corporation-ltd-1003455",
  "price": null,
  "ExchangeName": "bse",
  "sname": "I R F C",
  "tag": "News",
  "stockprice": "205.30",
  "chg": "1.65",
  "chgp": "0.81",
  "chgdir": 1,
  "score": 58,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003127,
  "Company": "<b>Rail</b> Vikas Nigam Ltd",
  "ScriptCode": 542649,
  "Symbol": "RVNL",
  "url": "https://www.marketsmojo.com/stocks-analysis/rail-vikas-nigam-1003127-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Rail Vikas",
  "tag": "Stock",
  "stockprice": "636.15",
  "chg": "25.60",
  "chgp": "4.19",
  "chgdir": 1,
  "score": 64,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003127,
  "Company": "<b>Rail</b> Vikas Nigam Ltd",
  "ScriptCode": 542649,
  "Symbol": "RVNL",
  "url": "https://www.marketsmojo.com/news/rail-vikas-nigam-ltd-1003127",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Rail Vikas",
  "tag": "News",
  "stockprice": "636.15",
  "chg": "25.60",
  "chgp": "4.19",
  "chgdir": 1,
  "score": 64,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003280,
  "Company": "Indian <b>Rail</b>way Catering & Tourism Corporation Ltd",
  "ScriptCode": 542830,
  "Symbol": "IRCTC",
  "url": "https://www.marketsmojo.com/stocks-analysis/indian-railway-catering-tourism-corporation-1003280-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "I R C T C",
  "tag": "Stock",
  "stockprice": "1035.55",
  "chg": "14.15",
  "chgp": "1.39",
  "chgdir": 1,
  "score": 72,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003280,
  "Company": "Indian <b>Rail</b>way Catering & Tourism Corporation Ltd",
  "ScriptCode": 542830,
  "Symbol": "IRCTC",
  "url": "https://www.marketsmojo.com/news/indian-railway-catering-tourism-corporation-ltd-1003280",
  "price": null,
  "ExchangeName": "bse",
  "sname": "I R C T C",
  "tag": "News",
  "stockprice": "1035.55",
  "chg": "14.15",
  "chgp": "1.39",
  "chgdir": 1,
  "score": 72,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003463,
  "Company": "<b>Rail</b>tel Corporation of India Ltd",
  "ScriptCode": 543265,
  "Symbol": "RAILTEL",
  "url": "https://www.marketsmojo.com/stocks-analysis/railtel-corporation-of-india-1003463-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Railtel Corpn.",
  "tag": "Stock",
  "stockprice": "519.50",
  "chg": "-2.10",
  "chgp": "-0.40",
  "chgdir": -1,
  "score": 71,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003463,
  "Company": "<b>Rail</b>tel Corporation of India Ltd",
  "ScriptCode": 543265,
  "Symbol": "RAILTEL",
  "url": "https://www.marketsmojo.com/news/railtel-corporation-of-india-ltd-1003463",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Railtel Corpn.",
  "tag": "News",
  "stockprice": "519.50",
  "chg": "-2.10",
  "chgp": "-0.40",
  "chgdir": -1,
  "score": 71,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 664903,
  "Company": "Texmaco <b>Rail</b> & Engineering Ltd",
  "ScriptCode": 533326,
  "Symbol": "TEXRAIL",
  "url": "https://www.marketsmojo.com/stocks-analysis/texmaco-rail-engineering-664903-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Texmaco Rail",
  "tag": "Stock",
  "stockprice": "284.65",
  "chg": "10.00",
  "chgp": "3.64",
  "chgdir": 1,
  "score": 61,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 664903,
  "Company": "Texmaco <b>Rail</b> & Engineering Ltd",
  "ScriptCode": 533326,
  "Symbol": "TEXRAIL",
  "url": "https://www.marketsmojo.com/news/texmaco-rail-engineering-ltd-664903",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Texmaco Rail",
  "tag": "News",
  "stockprice": "284.65",
  "chg": "10.00",
  "chgp": "3.64",
  "chgdir": 1,
  "score": 61,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 529147,
  "Company": "Oriental <b>Rail</b> Infrastructure Ltd",
  "ScriptCode": 531859,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/oriental-rail-infrastructure-529147-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Oriental Rail",
  "tag": "Stock",
  "stockprice": "378.55",
  "chg": "18.00",
  "chgp": "4.99",
  "chgdir": 1,
  "score": 75,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 529147,
  "Company": "Oriental <b>Rail</b> Infrastructure Ltd",
  "ScriptCode": 531859,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/oriental-rail-infrastructure-ltd-529147",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Oriental Rail",
  "tag": "News",
  "stockprice": "378.55",
  "chg": "18.00",
  "chgp": "4.99",
  "chgdir": 1,
  "score": 75,
  "scoretext": "Buy",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 102257,
  "Company": "K&R <b>Rail</b> Engineering Ltd",
  "ScriptCode": 514360,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/k-r-rail-engineering-102257-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "K&R Rail Engine.",
  "tag": "Stock",
  "stockprice": "491.00",
  "chg": "11.80",
  "chgp": "2.46",
  "chgdir": 1,
  "score": 42,
  "scoretext": "Sell",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 102257,
  "Company": "K&R <b>Rail</b> Engineering Ltd",
  "ScriptCode": 514360,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/k-r-rail-engineering-ltd-102257",
  "price": null,
  "ExchangeName": "bse",
  "sname": "K&R Rail Engine.",
  "tag": "News",
  "stockprice": "491.00",
  "chg": "11.80",
  "chgp": "2.46",
  "chgdir": 1,
  "score": 42,
  "scoretext": "Sell",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 919938,
  "Company": "NR Agarwal Industries Ltd. - N<b>RAIL</b>",
  "ScriptCode": 516082,
  "Symbol": "NRAIL",
  "url": "https://www.marketsmojo.com/stocks-analysis/nr-agarwal-industries-919938-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "NR Agarwal Inds",
  "tag": "Stock",
  "stockprice": "484.50",
  "chg": "-10.45",
  "chgp": "-2.11",
  "chgdir": -1,
  "score": 54,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 919938,
  "Company": "NR Agarwal Industries Ltd. - N<b>RAIL</b>",
  "ScriptCode": 516082,
  "Symbol": "NRAIL",
  "url": "https://www.marketsmojo.com/news/nr-agarwal-industries-ltd-919938",
  "price": null,
  "ExchangeName": "bse",
  "sname": "NR Agarwal Inds",
  "tag": "News",
  "stockprice": "484.50",
  "chg": "-10.45",
  "chgp": "-2.11",
  "chgdir": -1,
  "score": 54,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 421449,
  "Company": "Cressanda <b>Rail</b>way Solutions Ltd",
  "ScriptCode": 512379,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/cressanda-railway-solutions-421449-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Cressanda Railwa",
  "tag": "Stock",
  "stockprice": "12.18",
  "chg": "-0.26",
  "chgp": "-2.09",
  "chgdir": -1,
  "score": 51,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 421449,
  "Company": "Cressanda <b>Rail</b>way Solutions Ltd",
  "ScriptCode": 512379,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/cressanda-railway-solutions-ltd-421449",
  "price": null,
  "ExchangeName": "bse",
  "sname": "Cressanda Railwa",
  "tag": "News",
  "stockprice": "12.18",
  "chg": "-0.26",
  "chgp": "-2.09",
  "chgdir": -1,
  "score": 51,
  "scoretext": "Hold",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003080,
  "Company": "BCPL <b>Rail</b>way Infrastructure Ltd",
  "ScriptCode": 542057,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/stocks-analysis/bcpl-railway-infrastructure-1003080-0",
  "price": null,
  "ExchangeName": "bse",
  "sname": "BCPL Railway",
  "tag": "Stock",
  "stockprice": "103.75",
  "chg": "-2.10",
  "chgp": "-1.98",
  "chgdir": -1,
  "score": 43,
  "scoretext": "Sell",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
},
{
  "Id": 1003080,
  "Company": "BCPL <b>Rail</b>way Infrastructure Ltd",
  "ScriptCode": 542057,
  "Symbol": "",
  "url": "https://www.marketsmojo.com/news/bcpl-railway-infrastructure-ltd-1003080",
  "price": null,
  "ExchangeName": "bse",
  "sname": "BCPL Railway",
  "tag": "News",
  "stockprice": "103.75",
  "chg": "-2.10",
  "chgp": "-1.98",
  "chgdir": -1,
  "score": 43,
  "scoretext": "Sell",
  "stock_traded_status": "Active",
  "show_score": 1,
  "recurl": ""
}



  
  ],
  data: [

    //Indian Express
    { "Company": "Indian Express",
      "code": 200,
      "message": "success",
      "data": {
        "price_info": {
          "vol_msg": "Compared to 5 day average volume of 10.31 cr at 11:28 AM",
          "mcap_class": "Large Cap",
          "no_of_shares": 13068506000,
          "div_yeild": 0.74,
          "net_profit": 0,
          "pe_ratio": 41.44,
          "ind_pe_ratio": "23.54",
          "deb_equity": 8.54,
          "price_to_book": 5.52,
          "net_npa_perc": "",
          "gross_npa_perc": "",
          "p_adj_bv": "0",
          "ind_p_adj_bv": "3.24",
          "stock_status": "Active",
          "is_traded": 1,
          "mcap": 268427.11324,
          "roe": 13.31,
          "car": "",
          "roa": "",
          "net_sale": 0,
          "sector_chgp": -0.04,
          "index_label": "SENSEX",
          "5D_avg_vol": 106082151,
          "open_price": 207.7,
          "cmp": 205.4,
          "day_high": 209.05,
          "day_low": 201,
          "vol": 4797418,
          "dt": "2024-07-11 11:47:00",
          "val_trd": 983590625.45,
          "bid_price": 205.35,
          "bid_qty": 1088,
          "offer_price": 205.4,
          "offer_qty": 600,
          "mcap_grade": "1",
          "52wk_low_dt": "2023-07-17",
          "52wk_high_dt": "2024-07-09",
          "altm_high": 213,
          "altm_low_dt": "2022-06-20",
          "altm_high_dt": "2024-07-09",
          "altm_low": 19.3,
          "wk_high52": 213,
          "wk_low52": 32.35
        },
        "cover_page_data": {
          "cover_headline": "Healthy Growth in </br>Long Term Net Sales ",
          "cover_summary": [
            {
              "big_txt": "Bullish",
              "small_txt": "Technical Trend"
            },
            {
              "big_txt": "Market Beating Returns",
              "small_txt": "Over 3 Years"
            }
          ]
        },
        "score_text": "hold",
        "cover_clr": "coverhead-orange",
        "stock_details": {
          "sid": 1003455,
          "sname": "Indian Railway Finance Corporation Ltd",
          "short_name": "I R F C",
          "scripcode": "543257",
          "symbol": "IRFC",
          "isin": "INE053F01010",
          "status": "Active",
          "ind_code": 5,
          "ind_name": "Finance/NBFC",
          "sublisting": "Active",
          "alias": "",
          "fincode": 10026005,
          "fv": 10,
          "header_msg": "",
          "mcap_type": 1,
          "inc_mnth": "December",
          "inc_yr": "1986",
          "is_seasonal": "",
          "acc_ind_name": "NBFC",
          "hse_code": "562",
          "amfi_mcapsizerank": "midcap",
          "jan31_high_2018": {
            "nse": 0,
            "bse": 0
          },
          "updated_at": "2018-01-01",
          "nsedt": "2024-07-10",
          "bsedt": "2024-07-11"
        },
        "block_page": 0,
        "remaining_views": 0,
        "total_views": 0,
        "show_fallstock": "no"
      }
    },
  //TCS
  { 
    "Company":"TCS",
    "code": 200,
    "message": "success",
    "data": {
        "price_info": {
            "cmp": 3900.85,
            "open_price": 3944.65,
            "day_low": 3895.7,
            "day_high": 3979.9,
            "52wk_low_dt": "2023-07-12",
            "52wk_high_dt": "2024-03-18",
            "altm_low": 104.5,
            "altm_high": 4254.45,
            "altm_low_dt": "2008-10-27",
            "altm_high_dt": "2024-03-18",
            "vol_msg": "Compared to 5 day average volume of 6.75 lacs at 11:25 AM",
            "mcap_class": "Large Cap",
            "bid_price": 3901.05,
            "bid_qty": 162,
            "offer_price": 3902.95,
            "offer_qty": 100,
            "no_of_shares": 3618087518,
            "div_yeild": 1.87,
            "net_profit": 125020,
            "pe_ratio": 30.34,
            "ind_pe_ratio": "33.38",
            "deb_equity": -0.41,
            "price_to_book": 15.63,
            "net_npa_perc": "",
            "gross_npa_perc": "",
            "p_adj_bv": "0",
            "ind_p_adj_bv": "7.96",
            "stock_status": "Active",
            "dt": "2024-07-11 11:48:00",
            "vol": 55907,
            "mcap": 1411361.6694590298,
            "roe": 51.53,
            "car": "",
            "roa": "",
            "net_sale": 612370,
            "sector_chgp": 0.01,
            "index_label": "SENSEX",
            "5D_avg_vol": 757376.6,
            "vol_chgp": -55.75,
            "mcap_grade": "1",
            "is_traded": 1,
            "val_trd": 220150584.60000002,
            "wk_high52": 4254.45,
            "wk_low52": 3250
        },
        "cover_page_data": {
            "cover_headline": "Strong </br>Long Term Fundamentals ",
            "cover_summary": [
                {
                    "big_txt": "5 Consecutive Positive Results",
                    "small_txt": ""
                },
                {
                    "big_txt": "Mildly Bullish",
                    "small_txt": "Technical Trend"
                },
                {
                    "big_txt": "Fair",
                    "small_txt": "Valuation"
                },
                {
                    "big_txt": "Largest Company",
                    "small_txt": "in IT - Software  sector"
                }
            ]
        },
        "score_text": "buy",
        "cover_clr": "coverhead-green-light",
        "stock_details": {
            "sid": 513374,
            "sname": "Tata Consultancy Services Ltd.",
            "short_name": "TCS",
            "scripcode": 532540,
            "symbol": "TCS",
            "isin": "INE467B01029",
            "status": "Active",
            "ind_code": 57,
            "ind_name": "IT - Software ",
            "sublisting": "Active",
            "alias": "Tata Consultancy Services,TCS,TCS,INE467B01029,532540,TCS",
            "fincode": 132540,
            "fv": 1,
            "header_msg": "",
            "mcap_type": 1,
            "inc_mnth": "19-01",
            "inc_yr": "1995",
            "is_seasonal": 0,
            "acc_ind_code": 65,
            "acc_ind_name": "IT - Software ",
            "hse_code": 292,
            "amfi_mcapsizerank": "largecap",
            "jan31_high_2018": {
                "bse": 1573.55,
                "nse": 1575
            },
            "updated_at": "2018-01-01",
            "nsedt": "2024-07-10",
            "bsedt": "2024-07-11"
        },
        "block_page": 0,
        "remaining_views": 0,
        "total_views": 0,
        "show_fallstock": "no"
    }
},
  //HDFC

  { 
    "Company":"HDFC Bank",
    "code": 200,
    "message": "success",
    "data": {
        "price_info": {
            "cmp": 1606,
            "open_price": 1625.95,
            "day_low": 1601,
            "day_high": 1625.95,
            "52wk_low_dt": "2024-02-14",
            "52wk_high_dt": "2024-07-03",
            "altm_low": 3.23,
            "altm_high": 1791.9,
            "altm_low_dt": "1996-04-11",
            "altm_high_dt": "2024-07-03",
            "vol_msg": "Compared to 5 day average volume of 1.25 cr at 11:25 AM",
            "mcap_class": "Large Cap",
            "bid_price": 1606,
            "bid_qty": 861,
            "offer_price": 1606.8,
            "offer_qty": 64,
            "no_of_shares": 7608122302,
            "div_yeild": 1.2,
            "net_profit": 0,
            "pe_ratio": 20.35,
            "ind_pe_ratio": "19.36",
            "deb_equity": "",
            "price_to_book": 2.83,
            "net_npa_perc": 0.33,
            "gross_npa_perc": 1.12,
            "p_adj_bv": "2.83",
            "ind_p_adj_bv": "2.76",
            "stock_status": "Active",
            "dt": "2024-07-11 11:49:00",
            "vol": 399815,
            "mcap": 1227723,
            "roe": "",
            "car": 16.8,
            "roa": 1.68,
            "net_sale": 0,
            "sector_chgp": -0.77,
            "index_label": "SENSEX",
            "5D_avg_vol": 14046166,
            "vol_chgp": -30.34,
            "mcap_grade": "1",
            "is_traded": 1,
            "val_trd": 645091507.125,
            "wk_high52": 1791.9,
            "wk_low52": 1363.45
        },
        "cover_page_data": {
            "cover_headline": "Strong </br>Long Term Fundamentals ",
            "cover_summary": [
                {
                    "big_txt": "Very Positive",
                    "small_txt": "Results in Mar 24"
                },
                {
                    "big_txt": "Bullish",
                    "small_txt": "Technical Trend"
                },
                {
                    "big_txt": "Fair",
                    "small_txt": "Valuation"
                },
                {
                    "big_txt": " High (82.65%)",
                    "small_txt": "Institutional Holding"
                }
            ]
        },
        "score_text": "strong buy",
        "cover_clr": "coverhead-green",
        "stock_details": {
            "sid": 592009,
            "sname": "HDFC Bank Ltd.",
            "short_name": "HDFC Bank",
            "scripcode": 500180,
            "symbol": "HDFCBANK",
            "isin": "INE040A01034",
            "status": "Active",
            "ind_code": 50,
            "ind_name": "Private Banks",
            "sublisting": "Active",
            "alias": "HDFC Bank,HDFCBANK,HDFC Bank,INE040A01026,500180,HDFCBk",
            "fincode": 100180,
            "fv": 1,
            "header_msg": "",
            "mcap_type": 1,
            "inc_mnth": "30-08",
            "inc_yr": "1994",
            "is_seasonal": 1,
            "acc_ind_code": 15,
            "acc_ind_name": "Bank - Private",
            "hse_code": 336,
            "amfi_mcapsizerank": "largecap",
            "jan31_high_2018": {
                "bse": 1005.95,
                "nse": 1006.75
            },
            "updated_at": "2018-01-01",
            "nsedt": "2024-07-10",
            "bsedt": "2024-07-11"
        },
        "block_page": 0,
        "remaining_views": 0,
        "total_views": 0,
        "show_fallstock": "no"
    }
},
//Infosys
{ 
  "Company": "Infosys",
  "code": 200,
  "message": "success",
  "data": {
    "price_info": {
      "cmp": 1652,
      "open_price": 1655,
      "day_low": 1642.25,
      "day_high": 1665,
      "52wk_low_dt": "2023-07-21",
      "52wk_high_dt": "2024-02-06",
      "altm_low": 0.82,
      "altm_high": 1953.7,
      "altm_low_dt": "1995-05-03",
      "altm_high_dt": "2022-01-17",
      "vol_msg": "Compared to 5 day average volume of 28.89 lacs at 11:25 AM",
      "mcap_class": "Large Cap",
      "bid_price": 1652.1,
      "bid_qty": 1,
      "offer_price": 1652.5,
      "offer_qty": 17,
      "no_of_shares": 4152028475,
      "div_yeild": 2.79,
      "net_profit": 79750,
      "pe_ratio": 26.08,
      "ind_pe_ratio": "33.38",
      "deb_equity": -0.22,
      "price_to_book": 7.76,
      "net_npa_perc": "",
      "gross_npa_perc": "",
      "p_adj_bv": "0",
      "ind_p_adj_bv": "7.96",
      "stock_status": "Active",
      "dt": "2024-07-11 11:50:00",
      "vol": 40090,
      "mcap": 685915.10407,
      "roe": 29.77,
      "car": "",
      "roa": "",
      "net_sale": 379230,
      "sector_chgp": 0.01,
      "index_label": "SENSEX",
      "5D_avg_vol": 3327256.2,
      "vol_chgp": -19.13,
      "mcap_grade": "1",
      "is_traded": 1,
      "val_trd": 66293826.25,
      "wk_high52": 1731,
      "wk_low52": 1311.6
    },
    "cover_page_data": {
      "cover_headline": "Strong </br>Long Term Fundamentals ",
      "cover_summary": [
        {
          "big_txt": "Mildly Bullish",
          "small_txt": "Technical Trend"
        },
        {
          "big_txt": "Fair",
          "small_txt": "Valuation"
        },
        {
          "big_txt": " High (70.03%)",
          "small_txt": "Institutional Holding"
        },
        {
          "big_txt": "Second Largest Company",
          "small_txt": "in IT - Software  sector"
        }
      ]
    },
    "score_text": "buy",
    "cover_clr": "coverhead-green-light",
    "stock_details": {
      "sid": 399834,
      "sname": "Infosys Ltd.",
      "short_name": "Infosys",
      "scripcode": 500209,
      "symbol": "INFY",
      "isin": "INE009A01021",
      "status": "Active",
      "ind_code": 57,
      "ind_name": "IT - Software ",
      "sublisting": "Active",
      "alias": "Infosys,INFY,Infosys,INE009A01021,500209,Infy",
      "fincode": 100209,
      "fv": 5,
      "header_msg": "",
      "mcap_type": 1,
      "inc_mnth": "02-07",
      "inc_yr": "1981",
      "is_seasonal": 0,
      "acc_ind_code": 65,
      "acc_ind_name": "IT - Software ",
      "hse_code": 206,
      "amfi_mcapsizerank": "largecap",
      "jan31_high_2018": {
        "bse": 583,
        "nse": 583.3
      },
      "updated_at": "2018-01-01",
      "nsedt": "2024-07-10",
      "bsedt": "2024-07-11"
    },
    "block_page": 0,
    "remaining_views": 0,
    "total_views": 0,
    "show_fallstock": "no"
  }
},
 //ICICI 
{ 
  "Company":"ICICI ",
  "code": 200,
  "message": "success",
  "data": {
      "price_info": {
          "cmp": 1228.95,
          "open_price": 1245.05,
          "day_low": 1227.05,
          "day_high": 1257.65,
          "52wk_low_dt": "2023-10-26",
          "52wk_high_dt": "2024-07-10",
          "altm_low": 3.82,
          "altm_high": 1257.65,
          "altm_low_dt": "1999-02-09",
          "altm_high_dt": "2024-07-10",
          "vol_msg": "Compared to 5 day average volume of 48.56 lacs at 11:25 AM",
          "mcap_class": "Large Cap",
          "bid_price": 1228.55,
          "bid_qty": 38,
          "offer_price": 1228.95,
          "offer_qty": 70,
          "no_of_shares": 7037285189,
          "div_yeild": 0.64,
          "net_profit": 0,
          "pe_ratio": 21.38,
          "ind_pe_ratio": "19.36",
          "deb_equity": "",
          "price_to_book": 3.69,
          "net_npa_perc": 0.42,
          "gross_npa_perc": 2.81,
          "p_adj_bv": "3.69",
          "ind_p_adj_bv": "2.76",
          "stock_status": "Active",
          "dt": "2024-07-11 11:52:00",
          "vol": 99552,
          "mcap": 874840,
          "roe": "",
          "car": 15.6,
          "roa": 2.18,
          "net_sale": 0,
          "sector_chgp": -0.77,
          "index_label": "SENSEX",
          "5D_avg_vol": 5321587.8,
          "vol_chgp": -20.99,
          "mcap_grade": "1",
          "is_traded": 1,
          "val_trd": 123678427.19999999,
          "wk_high52": 1257.65,
          "wk_low52": 898.85
      },
      "cover_page_data": {
          "cover_headline": "Very Positive </br>Results in Mar 24 ",
          "cover_summary": [
              {
                  "big_txt": "Bullish",
                  "small_txt": "Technical Trend"
              },
              {
                  "big_txt": " High (90.4%)",
                  "small_txt": "Institutional Holding"
              },
              {
                  "big_txt": "Second Largest Company",
                  "small_txt": "in Private Banks sector"
              }
          ]
      },
      "score_text": "strong buy",
      "cover_clr": "coverhead-green",
      "stock_details": {
          "sid": 478299,
          "sname": "ICICI Bank Ltd.",
          "short_name": "ICICI Bank",
          "scripcode": 532174,
          "symbol": "ICICIBANK",
          "isin": "INE090A01021",
          "status": "Active",
          "ind_code": 50,
          "ind_name": "Private Banks",
          "sublisting": "Active",
          "alias": "ICICI Bank,ICICIBANK,ICICI Bank,INE090A01021,532174,ICICI Bk",
          "fincode": 132174,
          "fv": 2,
          "header_msg": "",
          "mcap_type": 1,
          "inc_mnth": "05-01",
          "inc_yr": "1994",
          "is_seasonal": 0,
          "acc_ind_code": 15,
          "acc_ind_name": "Bank - Private",
          "hse_code": 335,
          "amfi_mcapsizerank": "largecap",
          "jan31_high_2018": {
              "bse": 353.85,
              "nse": 353.95
          },
          "updated_at": "2018-01-01",
          "nsedt": "2024-07-10",
          "bsedt": "2024-07-11"
      },
      "block_page": 0,
      "remaining_views": 0,
      "total_views": 0,
      "show_fallstock": "no"
  }
},
  
  ]
};
